[IG]
ig = fsh-generated/resources/ImplementationGuide-johnmoehrke.testmermaid.example.json
# fhir2.base.template#current will show the problem, where as without #current the mermaid shows fine
template = fhir2.base.template#current
#template = fhir2.base.template
